apiVersion: v1
kind: Pod
metadata:  
  labels:
    run: app-consuming-pvc
  name: app-consuming-pvc
spec:
  volumes:
  - name: app-storage
    persistentVolumeClaim:
      claimName: db-pvc
  containers:
  - images: alpine
    name: app
    command : ["/bin/sh"]
    args: ["-c","while true; do sleep 60; done;"]
    volumeMounts:
      - mounthPath: "/mnt/data"
        name: app-storage