apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-app
  name: nginx-app
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - mountPath: /var/logs
      name: logs-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}