apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  volumes:
    - name: myvol
      emptyDir: {}
  containers:
  - name: busybox
    command : ["/bin/sh"]
    args: ["-c","while true; do sleep 3600; done;"]
    image: busybox        
    volumeMounts:
    - name: myvol
      mountPath: /etc/foo
  - name: busybox2
    command : ["/bin/sh"]
    args: ["-c","while true; do sleep 3600; done;"]
    image: busybox    
    volumeMounts:
    - name: myvol
      mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
