apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busyboxpvc
  name: busyboxpvc
spec:
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: mypvc
  containers:
  - image: busybox
    name: busyboxpvc
    command: ["/bin/sh"]
    args: ["-c","while true; do sleep 3600; done;"]
    resources: {}
    volumeMounts:
    - mountPath: "/etc/foo"
      name: myvol
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  
status: {}
