apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-allow
spec:
  podSelector:
    matchLabels:
      app: payment-processor
      role: api
  policyTypes:
    - Ingress    
  ingress:
    - from:        
        - namespaceSelector:
            matchLabels:
              app: coffeeshop
